### ISSUE TITLE
重构 MayDOS 0.0.1-Alpha

### ISSUE THREAD

**Issue by Buelie** [MayDOS-Team/MayDOS#4]
原MayDOS感觉好乱啊。所以我想重构。

完毕。

**Comment by Buelie** [comment]
当前进度:

# 增加
* **Message类，适合用于控制台输出**
* **File类，适用于文件处理**
* **Folder类，适用于文件夹处理**
* **Command类，适用于命令设计**

# 优化
* **显著提升性能，减少预加载内容**

**Comment by kuqilin** [comment]
现已完成重构
